/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lottery } from './Lottery.js';
export * as factories from './factories/index.js';
export { Lottery__factory } from './factories/Lottery__factory.js';