/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface LotteryInterface extends Interface {
    getFunction(nameOrSignature: "enter" | "getPlayers" | "manager" | "pickWinner" | "players"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'enter', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPlayers', values?: undefined): string;
encodeFunctionData(functionFragment: 'manager', values?: undefined): string;
encodeFunctionData(functionFragment: 'pickWinner', values?: undefined): string;
encodeFunctionData(functionFragment: 'players', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'enter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlayers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pickWinner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'players', data: BytesLike): Result;
  }

  

  export interface Lottery extends BaseContract {
    
    connect(runner?: ContractRunner | null): Lottery;
    waitForDeployment(): Promise<this>;

    interface: LotteryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    enter: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    getPlayers: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    manager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pickWinner: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    players: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'enter'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getPlayers'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'manager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pickWinner'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'players'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }