# Generated by Django 5.2.15 on 2026-06-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('quantity', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbanks.bloodbank')),
            ],
        ),
    ]
