// backend/config/drugCacheConstants.js

const LOCAL_CACHE_SOURCE = 'LOCAL_CACHE';
const NAME_CACHE_PREFIX = 'NAME:';
const PAIR_HASH_PREFIX = 'PAIR:';
const RXCHECK_SOURCE = 'RXCHECK';
const RXCHECK_NO_INTERACTION_SOURCE = 'RXCHECK_NO_INTERACTION';

module.exports = {
  LOCAL_CACHE_SOURCE,
  NAME_CACHE_PREFIX,
  PAIR_HASH_PREFIX,
  RXCHECK_SOURCE,
  RXCHECK_NO_INTERACTION_SOURCE,
};
