const USER_ROLES = ['PATIENT', 'PHYSICIAN', 'CMO', 'ADMIN', 'PHARMACIST'];
const ACCOUNT_STATUSES = ['ACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', 'DECEASED'];
const BIOLOGICAL_SEX = ['M', 'F', 'INTERSEX', 'UNKNOWN'];
const CONTACT_METHODS = ['SMS', 'EMAIL', 'PORTAL'];
const BLOOD_TYPES = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

const CLINICAL_DOMAINS = [
  'CARDIOLOGY',
  'PSYCHIATRY',
  'ONCOLOGY',
  'NEUROLOGY',
  'GENERAL_PRACTICE',
  'ENDOCRINOLOGY',
  'IMMUNOLOGY',
  'REPRODUCTIVE_HEALTH',
  'SUBSTANCE_USE',
  'INFECTIOUS_DISEASE',
];

const SENSITIVITY_CLASSIFICATIONS = ['STANDARD', 'SENSITIVE', 'HIGHLY_SENSITIVE'];
const DIAGNOSIS_STATUSES = ['ACTIVE', 'RESOLVED', 'CHRONIC', 'RULED_OUT'];
const DOSE_UNITS = ['mg', 'mcg', 'mL', 'units'];
const DOSE_ROUTES = ['ORAL', 'IV', 'IM', 'SUBCUTANEOUS', 'TOPICAL', 'INHALED'];
const ALLERGY_SEVERITIES = ['MILD', 'MODERATE', 'SEVERE', 'LIFE_THREATENING'];
const INTERACTION_TIERS = ['HARD_STOP', 'SOFT_WARNING', 'INFORMATIONAL'];
const LAB_INTERPRETATIONS = ['NORMAL', 'LOW', 'HIGH', 'CRITICAL_LOW', 'CRITICAL_HIGH'];

const PERMISSION_TIERS = [
  'VIEW_ONLY',
  'VIEW_ADD_NOTES',
  'VIEW_ADD_PRESCRIPTIONS',
  'FULL_WRITE',
];

const CONSENT_STATUSES = [
  'PENDING_PATIENT_CONFIRMATION',
  'ACTIVE',
  'EXPIRED',
  'REVOKED',
  'SUPERSEDED',
];

const CONSENT_ORIGINS = ['PATIENT_PORTAL', 'IN_PERSON_SIGNED', 'BREAK_GLASS_OVERRIDE'];
const CONFIRMATION_METHODS = ['PORTAL_2FA', 'BIOMETRIC', 'SIGNED_FORM', 'VERBAL_WITNESSED'];

const BREAK_GLASS_TIERS = ['TIER_1_SOFT_OVERRIDE', 'TIER_2_HARD_OVERRIDE'];
const CLINICAL_JUSTIFICATION_CODES = [
  'EMERGENCY_DEPARTMENT',
  'UNCONSCIOUS_PATIENT',
  'LIFE_THREATENING_EVENT',
  'TRANSFER_OF_CARE',
];
const NOTIFICATION_CHANNELS = ['SMS', 'EMAIL', 'PORTAL_ALERT'];
const REVIEW_STATUSES = ['PENDING', 'IN_REVIEW', 'CLEARED', 'FLAGGED_FOR_INVESTIGATION'];
const BREAK_GLASS_RECORD_PHASES = ['REQUEST', 'APPROVAL', 'DENIAL'];

const BREAK_GLASS_TIER1_SESSION_HOURS = 4;
const BREAK_GLASS_TIER2_SESSION_HOURS = 8;
const COMPLIANCE_ESCALATION_SLA_HOURS = 24;
const BREAK_GLASS_TIER2_RETROSPECTIVE_REVIEW_DAYS = 7;

const ADR_REPORTED_BY = ['PATIENT', 'PHYSICIAN', 'PHARMACIST'];
const ADR_SEVERITIES = ['NON_SERIOUS', 'SERIOUS', 'LIFE_THREATENING', 'FATAL'];
const ADR_OUTCOMES = ['RECOVERING', 'RECOVERED', 'NOT_RECOVERED', 'UNKNOWN', 'FATAL'];
const RECHALLENGE = ['YES', 'NO', 'UNKNOWN'];
const DECHALLENGE = ['YES_SYMPTOMS_RESOLVED', 'YES_SYMPTOMS_PERSISTED', 'NOT_APPLICABLE'];

const EVIDENCE_LEVELS = ['CONTRAINDICATED', 'MAJOR', 'MODERATE', 'MINOR'];

const DRUG_VALIDATION_DECISIONS = ['HARD_STOP', 'SOFT_WARNING', 'SAFE'];

const PRESCRIPTION_IMAGE_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'application/pdf',
];

const AUDIT_EVENT_TYPES = [
  'CONSENT_CREATED',
  'CONSENT_CONFIRMED',
  'CONSENT_RENEWED',
  'CONSENT_REVOKED',
  'CONSENT_EXPIRED',
  'BREAK_GLASS_INITIATED',
  'BREAK_GLASS_APPROVED',
  'BREAK_GLASS_DENIED',
  'PRESCRIPTION_VALIDATED',
  'PRESCRIPTION_ACKNOWLEDGED',
  'PRESCRIPTION_COMMITTED',
  'PRESCRIPTION_DISCONTINUED',
  'ADR_REPORTED',
  'ADR_REGULATORY_SUBMITTED',
  'PRESCRIPTION_IMAGE_UPLOADED',
  'PRESCRIPTION_IMAGE_DELETED',
];

const MAX_CONSENT_WINDOW_DAYS = 90;

module.exports = {
  USER_ROLES,
  ACCOUNT_STATUSES,
  BIOLOGICAL_SEX,
  CONTACT_METHODS,
  BLOOD_TYPES,
  CLINICAL_DOMAINS,
  SENSITIVITY_CLASSIFICATIONS,
  DIAGNOSIS_STATUSES,
  DOSE_UNITS,
  DOSE_ROUTES,
  ALLERGY_SEVERITIES,
  INTERACTION_TIERS,
  LAB_INTERPRETATIONS,
  PERMISSION_TIERS,
  CONSENT_STATUSES,
  CONSENT_ORIGINS,
  CONFIRMATION_METHODS,
  BREAK_GLASS_TIERS,
  CLINICAL_JUSTIFICATION_CODES,
  NOTIFICATION_CHANNELS,
  REVIEW_STATUSES,
  BREAK_GLASS_RECORD_PHASES,
  BREAK_GLASS_TIER1_SESSION_HOURS,
  BREAK_GLASS_TIER2_SESSION_HOURS,
  COMPLIANCE_ESCALATION_SLA_HOURS,
  BREAK_GLASS_TIER2_RETROSPECTIVE_REVIEW_DAYS,
  ADR_REPORTED_BY,
  ADR_SEVERITIES,
  ADR_OUTCOMES,
  RECHALLENGE,
  DECHALLENGE,
  EVIDENCE_LEVELS,
  DRUG_VALIDATION_DECISIONS,
  PRESCRIPTION_IMAGE_MIME_TYPES,
  AUDIT_EVENT_TYPES,
  MAX_CONSENT_WINDOW_DAYS,
};
